#服务配置
server:
  port: 9001
#spring配置
spring:
  #1.应用配置
  application:
    name: company #指定服务名
  #2.数据库连接池
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hrm?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
  #3.JPA
  jpa:
    database: MySQL
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: update

  redis:
    host: 127.0.0.1
    port: 6379

  #微服务注册到eureka配置
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:6868/eureka/